--[[
    =====================================================================
    Addon        : Enjoy Cigarettes
    Link         : https://www.moddb.com/mods/stalker-anomaly/addons/dltx-enjoy-cigarettes
    Author       : Tosox
	Date         : 22.04.2023
    Last Edit    : 09.06.2026
    =====================================================================
--]]

local defaults = {
    ["quickslot_bind"] = true,
    ["modifier"] = 1,
    ["animation"] = 1,
    ["invert"] = false
}

function get_config(key)
    if ui_mcm then return ui_mcm.get("enjoy_cigs/" .. key) else return defaults[key] end
end

function on_mcm_load()
    return {
        id = "enjoy_cigs", sh = true, gr = {
            { id = "title", type = "slide", link = "ui_options_slider_alife", text = "ui_mcm_enjoy_cigs_title", size = { 512, 50 }, spacing = 20 },
            { id = "animation", type = "list", val = 2, def = defaults["animation"],
                content = {
                    { 1, "anim_default" },
                    { 2, "anim_asnen" }
                }
            },
            { id = "invert", type = "check", val = 1, def = defaults["invert"] },
            { id = "quickslot_bind", type = "check", val = 1, def = defaults["quickslot_bind"] },
            { id = "modifier", type = ui_mcm.kb_mod_radio, val = 2, def = defaults["modifier"],
                content = {
                    { 0, "kb_mod_none" },
                    { 1, "kb_mod_shift" },
                    { 2, "kb_mod_ctrl" },
                    { 3, "kb_mod_alt" }
                }
            }
        }
    }
end
