name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        required: true
        default: v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create release zip
      run: |
        zip -r Enjoy-Cigarettes-${{ github.event.inputs.version }}.zip gamedata/ CHANGELOG.md LICENSE README.md

    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.version }}
        name: ${{ github.event.inputs.version }}
        files: |
          Enjoy-Cigarettes-${{ github.event.inputs.version }}.zip
        draft: false
        prerelease: false
        make_latest: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
